# Development Profile
spring.config.activate.on-profile=dev

# Database
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.root=DEBUG
logging.level.com.starlink=TRACE

# Security (menos estricto en dev)
jwt.expiration=86400000

# Email (usar consola en dev)
spring.mail.host=smtp.mailtrap.io
spring.mail.port=2525

# DevTools
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# Swagger habilitado
springdoc.swagger-ui.enabled=true
